version: '3.9'

services:
  postgres4:
    image: postgres:13
    environment:
      POSTGRES_DB: server4_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres4_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      postgres4:
        condition: service_healthy

volumes:
  postgres4_data:
